#version 460

#extension GL_EXT_nonuniform_qualifier : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout(set = 1, binding = 0, rgba32f) uniform image2D diffuseSH[];
layout(set = 1, binding = 0, rgba32f) uniform image2D diffuseSH2[];

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    for (int i = 0; i < 9; i++) {
        imageStore(diffuseSH2[i], pixel, imageLoad(diffuseSH[i], pixel));
    }
}